
title: My Resume
url: 'http://vineeth.github.io'
baseurl: '/Resume' #change it according to your repository name



# Profile information
yourname: Vineeth Karanam  ## put your name
title: 'SOFTWARE DEVELOPER'  ## your title
location: Noida, UP


## Social Profiles
facebook: https://www.facebook.com/vineeth.karanam  ## your facebook account url
twitter: https://twitter.com/vineeth_karanam  ## your twitter account url
linkedin: https://www.linkedin.com/in/vineeth-karanam/  ## your linkedin account url
github: https://github.com/vineethpisvas1  ## you github account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
