
title: My Resume
url: 'http://vineethpisvas1.github.io'
baseurl: '/resume' #change it according to your repository name



# Profile information
yourname: Vineeth Karanam  ## put your name
title: 'Software Development Engineer'  ## your title
location: Noida, UP


## Social Profiles
facebook: https://www.facebook.com/vineeth.karanam  ## your facebook account url
twitter: https://twitter.com/vineeth_karanam  ## your twitter account url
linkedin: https://www.linkedin.com/in/vineeth-karanam/  ## your linkedin account url
github: https://github.com/vineethpisvas1  ## you github account url



# Update all the sections by editing the files inside _includes folder.
